# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Michael Boyd
tagline:          'software engineer and writer'
description:      'Working for the Sovrin Foundation, Amazon SWE intern 2018,
                  BYU 2019 CS graduate, interested in using technology to improve education and healthcare.'
url:              http://michaelboyd.me
baseurl:          /

author:
  name:           'Michael Boyd'
  url:            https://github.com/michaeldboyd

gems:          [jekyll-paginate, jekyll-gist]

paginate:         5

# Custom vars
version:          2.1.0


github:
  repo:           https://github.com/michaeldboyd/michaeldboyd.github.io
